
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/click_uz_cards
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ismoil_0709
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: click-uz-cards
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8741/eureka
server:
  port: 4432